In [82]:
import pandas as pd
import numpy as np

In [83]:
appoint = pd.read_excel('../file/使用情况测试.xlsx')

In [84]:
appoint

,3.13 Monday,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,预约编号,预约人,人员需求,NaN,NaN,NaN,NaN,使用时段,人数,事件
1,NaN,NaN,Sound insulation,Facility,Spatial properties,refurniture,Specify the space,NaN,NaN,NaN
2,1,Teacher,Excellent,Projector,Close,NaN,Not specified,8：00-10：00,67,上课
3,2,Teacher,Excellent,Projector,NaN,NaN,NaN,9：00-11：00,36,上课
4,3,Teacher,Excellent,Projector,NaN,NaN,NaN,10：00-12：00,72,上课
5,4,Teacher,Excellent,NaN,Close,NaN,NaN,9：00-12：00,60,上课
6,5,Teacher,Excellent,NaN,NaN,NaN,NaN,9：00-12：00,37,上课
7,6,Teacher,Excellent,Projector,NaN,NaN,NaN,8：00-10：00,77,上课
8,7,Teacher,Excellent,Projector,Not specified,No,NaN,9：00-11：00,37,上课
9,8,Teacher,Excellent,Projector,Close,Yes,NaN,11：00-12：00,26,会议
10,9,Teacher,NaN,NaN,NaN,NaN,NaN,13：00-15：00,79,上课
11,10,Teacher,Excellent,NaN,NaN,NaN,NaN,14：00-16：00,37,上课
12,11,Student,Excellent,Projector,Close,Not specified,NaN,13：00-14：00,26,NaN
13,12,Teacher,Excellent,NaN,Close,NaN,NaN,15：00-17：00,77,上课
14,13,Teacher,Excellent,Projector,Close,NaN,NaN,16：00-18：00,76,上课
15,14,Teacher,Excellent,NaN,NaN,NaN,NaN,16：00-18：00,37,上课
16,15,Teacher,Excellent,Projector,Close,NaN,NaN,16：00-18：00,76,上课
17,16,Teacher,Excellent,NaN,NaN,NaN,NaN,16：00-18：00,37,上课
18,17,Student,Excellent,Projector,Close,Not specified,NaN,13：00-14：00,26,NaN
19,18,Teacher,Excellent,Projector,Close,NaN,NaN,14：00-16：00,39,上课
20,19,Student,Not specified,Projector,NaN,NaN,NaN,9：00-12：00,5,交流
21,20,Student,Not specified,Not specified,Open,Yes,NaN,8：00-10：00,6,交流
22,21,Student,Not specified,Projector,Close,Yes,NaN,8：00-10：00,9,自习
23,22,Student,Not specified,Projector,Close,Yes,NaN,8：00-10：00,5,会议
24,23,Student,Not specified,Not specified,Open,Yes,NaN,8：00-10：00,10,交流
25,24,Student,Not specified,Not specified,Open,Yes,NaN,8：00-10：00,4,交流
26,25,Student,Not specified,Not specified,Open,No,NaN,8：00-9：00,8,咖啡
27,26,Student,Not specified,Not specified,Open,No,NaN,8：00-9：00,6,咖啡
28,27,Student,Not specified,Not specified,Open,Not specified,NaN,8：00-10：00,8,咖啡
29,28,Student,Not specified,Not specified,Open,Not specified,NaN,8：00-10：00,10,咖啡
30,29,Student,Not specified,Not specified,Open,Not specified,NaN,9：00-10：00,12,咖啡
31,30,Student,Not specified,Not specified,Open,Not specified,NaN,9：00-10：00,10,咖啡
32,31,Student,Not specified,Not specified,Open,Not specified,NaN,9：00-12：00,6,咖啡
33,32,Student,Not specified,Not specified,Open,Not specified,NaN,10：00-12：00,14,咖啡
34,33,Student,Not specified,Not specified,Open,Not specified,NaN,11：00-12：00,20,咖啡
35,34,Student,Not specified,Not specified,Open,Not specified,NaN,13：00-15：00,20,咖啡
36,35,Student,Not specified,Not specified,Open,Not specified,NaN,13：00-15：00,8,咖啡
37,36,Student,Not specified,Not specified,Open,Not specified,NaN,13：00-14：00,8,咖啡
38,37,Student,Not specified,Not specified,Open,Not specified,NaN,14：00-17：00,23,咖啡
39,38,Student,Not specified,Not specified,Open,Not specified,NaN,14：00-17：00,23,咖啡
40,39,Student,Not specified,Not specified,Not specified,Not specified,NaN,15：00-18：00,23,咖啡
41,40,Student,Not specified,Not specified,Open,Not specified,NaN,15：00-18：00,6,交流
42,41,Student,Not specified,Not specified,Not specified,Not specified,NaN,17：00-18：00,6,交流
43,42,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-18：00,10,固定工位
44,43,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-20：00,5,固定工位
45,44,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-18：00,10,固定工位
46,45,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-20：00,5,固定工位
47,46,Student,Not specified,Not specified,Not specified,Not specified,NaN,18：00-20：00,11,固定工位
48,47,Student,Not specified,Computer,Not specified,Not specified,NaN,8：00-12：00,11,固定工位
49,48,Student,NaN,NaN,NaN,NaN,阅览,8：00-12：00,21,NaN
50,49,Student,NaN,NaN,NaN,NaN,阅览,9：00-12：00,17,NaN
51,50,Student,NaN,Shelves,NaN,NaN,NaN,10：00-12：00,12,NaN
52,51,Student,Not specified,Shelves,NaN,NaN,阅览,13：00-17：00,21,NaN
53,52,Student,Not specified,Shelves,NaN,NaN,阅览,14：00-17：00,17,阅览
54,53,Student,Not specified,Shelves,NaN,NaN,阅览,15：00-20：00,27,阅览
55,54,Student,Not specified,Shelves,NaN,NaN,阅览,15：00-20：00,27,阅览
56,55,Student,Not specified,Shelves,NaN,NaN,阅览,15：00-20：00,27,阅览
57,56,Student,Not specified,Shelves,NaN,NaN,阅览,16：00-19：00,31,阅览
58,57,Student,Not specified,Shelves,NaN,NaN,阅览,19：00-21：00,37,阅览
59,58,Student,Not specified,Shelves,NaN,NaN,阅览,19：00-21：00,37,阅览

In [85]:
# 删除前两行，修改列名
appoint.columns = ['预约编号','预约人','soundi','facility','sproperty','refur','specification','time','num','events']

In [86]:
appoint = appoint[2:].reset_index(drop=True)
appoint

,预约编号,预约人,soundi,facility,sproperty,refur,specification,time,num,events
0,1,Teacher,Excellent,Projector,Close,NaN,Not specified,8：00-10：00,67,上课
1,2,Teacher,Excellent,Projector,NaN,NaN,NaN,9：00-11：00,36,上课
2,3,Teacher,Excellent,Projector,NaN,NaN,NaN,10：00-12：00,72,上课
3,4,Teacher,Excellent,NaN,Close,NaN,NaN,9：00-12：00,60,上课
4,5,Teacher,Excellent,NaN,NaN,NaN,NaN,9：00-12：00,37,上课
5,6,Teacher,Excellent,Projector,NaN,NaN,NaN,8：00-10：00,77,上课
6,7,Teacher,Excellent,Projector,Not specified,No,NaN,9：00-11：00,37,上课
7,8,Teacher,Excellent,Projector,Close,Yes,NaN,11：00-12：00,26,会议
8,9,Teacher,NaN,NaN,NaN,NaN,NaN,13：00-15：00,79,上课
9,10,Teacher,Excellent,NaN,NaN,NaN,NaN,14：00-16：00,37,上课
10,11,Student,Excellent,Projector,Close,Not specified,NaN,13：00-14：00,26,NaN
11,12,Teacher,Excellent,NaN,Close,NaN,NaN,15：00-17：00,77,上课
12,13,Teacher,Excellent,Projector,Close,NaN,NaN,16：00-18：00,76,上课
13,14,Teacher,Excellent,NaN,NaN,NaN,NaN,16：00-18：00,37,上课
14,15,Teacher,Excellent,Projector,Close,NaN,NaN,16：00-18：00,76,上课
15,16,Teacher,Excellent,NaN,NaN,NaN,NaN,16：00-18：00,37,上课
16,17,Student,Excellent,Projector,Close,Not specified,NaN,13：00-14：00,26,NaN
17,18,Teacher,Excellent,Projector,Close,NaN,NaN,14：00-16：00,39,上课
18,19,Student,Not specified,Projector,NaN,NaN,NaN,9：00-12：00,5,交流
19,20,Student,Not specified,Not specified,Open,Yes,NaN,8：00-10：00,6,交流
20,21,Student,Not specified,Projector,Close,Yes,NaN,8：00-10：00,9,自习
21,22,Student,Not specified,Projector,Close,Yes,NaN,8：00-10：00,5,会议
22,23,Student,Not specified,Not specified,Open,Yes,NaN,8：00-10：00,10,交流
23,24,Student,Not specified,Not specified,Open,Yes,NaN,8：00-10：00,4,交流
24,25,Student,Not specified,Not specified,Open,No,NaN,8：00-9：00,8,咖啡
25,26,Student,Not specified,Not specified,Open,No,NaN,8：00-9：00,6,咖啡
26,27,Student,Not specified,Not specified,Open,Not specified,NaN,8：00-10：00,8,咖啡
27,28,Student,Not specified,Not specified,Open,Not specified,NaN,8：00-10：00,10,咖啡
28,29,Student,Not specified,Not specified,Open,Not specified,NaN,9：00-10：00,12,咖啡
29,30,Student,Not specified,Not specified,Open,Not specified,NaN,9：00-10：00,10,咖啡
30,31,Student,Not specified,Not specified,Open,Not specified,NaN,9：00-12：00,6,咖啡
31,32,Student,Not specified,Not specified,Open,Not specified,NaN,10：00-12：00,14,咖啡
32,33,Student,Not specified,Not specified,Open,Not specified,NaN,11：00-12：00,20,咖啡
33,34,Student,Not specified,Not specified,Open,Not specified,NaN,13：00-15：00,20,咖啡
34,35,Student,Not specified,Not specified,Open,Not specified,NaN,13：00-15：00,8,咖啡
35,36,Student,Not specified,Not specified,Open,Not specified,NaN,13：00-14：00,8,咖啡
36,37,Student,Not specified,Not specified,Open,Not specified,NaN,14：00-17：00,23,咖啡
37,38,Student,Not specified,Not specified,Open,Not specified,NaN,14：00-17：00,23,咖啡
38,39,Student,Not specified,Not specified,Not specified,Not specified,NaN,15：00-18：00,23,咖啡
39,40,Student,Not specified,Not specified,Open,Not specified,NaN,15：00-18：00,6,交流
40,41,Student,Not specified,Not specified,Not specified,Not specified,NaN,17：00-18：00,6,交流
41,42,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-18：00,10,固定工位
42,43,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-20：00,5,固定工位
43,44,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-18：00,10,固定工位
44,45,Student,Not specified,Not specified,Not specified,Not specified,NaN,8：00-20：00,5,固定工位
45,46,Student,Not specified,Not specified,Not specified,Not specified,NaN,18：00-20：00,11,固定工位
46,47,Student,Not specified,Computer,Not specified,Not specified,NaN,8：00-12：00,11,固定工位
47,48,Student,NaN,NaN,NaN,NaN,阅览,8：00-12：00,21,NaN
48,49,Student,NaN,NaN,NaN,NaN,阅览,9：00-12：00,17,NaN
49,50,Student,NaN,Shelves,NaN,NaN,NaN,10：00-12：00,12,NaN
50,51,Student,Not specified,Shelves,NaN,NaN,阅览,13：00-17：00,21,NaN
51,52,Student,Not specified,Shelves,NaN,NaN,阅览,14：00-17：00,17,阅览
52,53,Student,Not specified,Shelves,NaN,NaN,阅览,15：00-20：00,27,阅览
53,54,Student,Not specified,Shelves,NaN,NaN,阅览,15：00-20：00,27,阅览
54,55,Student,Not specified,Shelves,NaN,NaN,阅览,15：00-20：00,27,阅览
55,56,Student,Not specified,Shelves,NaN,NaN,阅览,16：00-19：00,31,阅览
56,57,Student,Not specified,Shelves,NaN,NaN,阅览,19：00-21：00,37,阅览
57,58,Student,Not specified,Shelves,NaN,NaN,阅览,19：00-21：00,37,阅览

### soundi

In [87]:
set(appoint['soundi'])

{'Excellent', 'Not specified', nan}

In [88]:
soundi_mapping = {
    'Excellent':2,
    'Not specified':0,
}
# 总可以选择大于等于自身隔音等级的空间
appoint['soundi']= appoint['soundi'].apply(lambda x: soundi_mapping.get(x,0)) #除上述映射其余置为0

### facility

In [89]:
set(appoint['facility'])

{'Computer', 'Not specified', 'Projector', 'Shelves', nan}

In [90]:
# 数据映射表
# facility_mapping = {
#     '0':0,
#     '1| Projector':1,
#     '1| Board':2,
#     '1| Computer':3,
#     '1| Shelves':4,
#     '1| 3D printer':5,
#     '1| Eye tracker':6,
#     '1| EEG':7,
#     '1| Audio-visual equipment':8
# }
facility_mapping = {
    '0':0,
    'Projector':1,
    '1| Board':2,
    'Computer':3,
    'Shelves':4,
    '1| 3D printer':5,
    '1| Eye tracker':6,
    '1| EEG':7,
    '1| Audio-visual equipment':8
}
# 根据映射修改列
appoint['facility'] = appoint['facility'].apply(lambda x: facility_mapping.get(x, 0)) #若存在key则映射，不能则0

### sproperty

In [91]:
set(appoint['sproperty'])

{'Close', 'Not specified', 'Open', nan}

In [92]:
# 映射
sproperty_mapping ={
     'Close':0,
     'Open':1,
} #1open,0close,nan无要求
appoint['sproperty'] = appoint['sproperty'].apply(lambda x: sproperty_mapping.get(x,2))
# 开放可以分配到任意空间<2；没有预约要求认为预约开放空间<2

### refur

In [93]:
set(appoint['refur'])

{'No', 'Not specified', 'Yes', nan}

In [94]:
# 映射
refur_mapping ={
     'Yes':1,
} #家具需要重新排布选择1，其余都选择0，>0或者>-1都可以选择
appoint['refur'] = appoint['refur'].apply(lambda x:refur_mapping.get(x,0))

### specification

In [95]:
set(appoint['specification'])

{'Not specified', nan, '阅览'}

In [96]:
# specification_mapping = {
#     'Not specified':0,
#     nan:0,
# }

In [97]:
appoint

,预约编号,预约人,soundi,facility,sproperty,refur,specification,time,num,events
0,1,Teacher,2,1,0,0,Not specified,8：00-10：00,67,上课
1,2,Teacher,2,1,2,0,NaN,9：00-11：00,36,上课
2,3,Teacher,2,1,2,0,NaN,10：00-12：00,72,上课
3,4,Teacher,2,0,0,0,NaN,9：00-12：00,60,上课
4,5,Teacher,2,0,2,0,NaN,9：00-12：00,37,上课
5,6,Teacher,2,1,2,0,NaN,8：00-10：00,77,上课
6,7,Teacher,2,1,2,0,NaN,9：00-11：00,37,上课
7,8,Teacher,2,1,0,1,NaN,11：00-12：00,26,会议
8,9,Teacher,0,0,2,0,NaN,13：00-15：00,79,上课
9,10,Teacher,2,0,2,0,NaN,14：00-16：00,37,上课
10,11,Student,2,1,0,0,NaN,13：00-14：00,26,NaN
11,12,Teacher,2,0,0,0,NaN,15：00-17：00,77,上课
12,13,Teacher,2,1,0,0,NaN,16：00-18：00,76,上课
13,14,Teacher,2,0,2,0,NaN,16：00-18：00,37,上课
14,15,Teacher,2,1,0,0,NaN,16：00-18：00,76,上课
15,16,Teacher,2,0,2,0,NaN,16：00-18：00,37,上课
16,17,Student,2,1,0,0,NaN,13：00-14：00,26,NaN
17,18,Teacher,2,1,0,0,NaN,14：00-16：00,39,上课
18,19,Student,0,1,2,0,NaN,9：00-12：00,5,交流
19,20,Student,0,0,1,1,NaN,8：00-10：00,6,交流
20,21,Student,0,1,0,1,NaN,8：00-10：00,9,自习
21,22,Student,0,1,0,1,NaN,8：00-10：00,5,会议
22,23,Student,0,0,1,1,NaN,8：00-10：00,10,交流
23,24,Student,0,0,1,1,NaN,8：00-10：00,4,交流
24,25,Student,0,0,1,0,NaN,8：00-9：00,8,咖啡
25,26,Student,0,0,1,0,NaN,8：00-9：00,6,咖啡
26,27,Student,0,0,1,0,NaN,8：00-10：00,8,咖啡
27,28,Student,0,0,1,0,NaN,8：00-10：00,10,咖啡
28,29,Student,0,0,1,0,NaN,9：00-10：00,12,咖啡
29,30,Student,0,0,1,0,NaN,9：00-10：00,10,咖啡
30,31,Student,0,0,1,0,NaN,9：00-12：00,6,咖啡
31,32,Student,0,0,1,0,NaN,10：00-12：00,14,咖啡
32,33,Student,0,0,1,0,NaN,11：00-12：00,20,咖啡
33,34,Student,0,0,1,0,NaN,13：00-15：00,20,咖啡
34,35,Student,0,0,1,0,NaN,13：00-15：00,8,咖啡
35,36,Student,0,0,1,0,NaN,13：00-14：00,8,咖啡
36,37,Student,0,0,1,0,NaN,14：00-17：00,23,咖啡
37,38,Student,0,0,1,0,NaN,14：00-17：00,23,咖啡
38,39,Student,0,0,2,0,NaN,15：00-18：00,23,咖啡
39,40,Student,0,0,1,0,NaN,15：00-18：00,6,交流
40,41,Student,0,0,2,0,NaN,17：00-18：00,6,交流
41,42,Student,0,0,2,0,NaN,8：00-18：00,10,固定工位
42,43,Student,0,0,2,0,NaN,8：00-20：00,5,固定工位
43,44,Student,0,0,2,0,NaN,8：00-18：00,10,固定工位
44,45,Student,0,0,2,0,NaN,8：00-20：00,5,固定工位
45,46,Student,0,0,2,0,NaN,18：00-20：00,11,固定工位
46,47,Student,0,3,2,0,NaN,8：00-12：00,11,固定工位
47,48,Student,0,0,2,0,阅览,8：00-12：00,21,NaN
48,49,Student,0,0,2,0,阅览,9：00-12：00,17,NaN
49,50,Student,0,4,2,0,NaN,10：00-12：00,12,NaN
50,51,Student,0,4,2,0,阅览,13：00-17：00,21,NaN
51,52,Student,0,4,2,0,阅览,14：00-17：00,17,阅览
52,53,Student,0,4,2,0,阅览,15：00-20：00,27,阅览
53,54,Student,0,4,2,0,阅览,15：00-20：00,27,阅览
54,55,Student,0,4,2,0,阅览,15：00-20：00,27,阅览
55,56,Student,0,4,2,0,阅览,16：00-19：00,31,阅览
56,57,Student,0,4,2,0,阅览,19：00-21：00,37,阅览
57,58,Student,0,4,2,0,阅览,19：00-21：00,37,阅览

In [98]:
appoint.to_excel('appoint.xlsx')